name: Test Python Prerelease
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-on-prerelease-python:
    runs-on: ubuntu-latest

    container: ghcr.io/corbel-spatial/here-be-dragons:next

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            pyproject.toml
            README.md
            src
            tests
          sparse-checkout-cone-mode: false

      - name: Run tests
        run: |
          docker run --name tester --rm -id --mount type=bind,source=./,target=/root/checkout ghcr.io/corbel-spatial/here-be-dragons:next
          docker exec -w /root/checkout tester uv pip install --system . pytest
          docker exec -w /root/checkout tester pytest
